---
title: "Number of consultations vs Health Spending (% GDP)"
output: html_document
date: "2022-11-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
high_inc_countries <- c("LUX", "IRL", "NOR",
                        "CHE", "USA", "DNK",
                        "NLD", "AUS", "SWE",
                        "AUT")
low_inc_countries <- c("IND", "IDN", "ZAF",
                       "BRA", "CHN", "COL",
                       "MEX", "CRI", "CHL",
                       "RUS")
```

```{r}
md_consult_per_capita_hi <- read.csv("oecd.csv") %>% 
  filter(COU %in% high_inc_countries,
         VAR == "CONSCOVI") %>% 
  select("COU", "Country", "Value", "Year")

md_consult_per_capita_lo <- read.csv("oecd.csv") %>% 
  filter(COU %in% low_inc_countries,
         VAR == "CONSCOVI") %>% 
  select("COU", "Country", "Value", "Year")

```

```{r}
health_spending_pcgdp_hi <- read.csv("HealthSpending.csv") %>% 
  filter(LOCATION %in% high_inc_countries,
         SUBJECT == "TOT",
         MEASURE == "PC_GDP") %>% 
  select("LOCATION", "Value", "TIME")
colnames(health_spending_pcgdp_hi) <- c("COU", "Value", "Year")

health_spending_pcgdp_lo <- read.csv("HealthSpending.csv") %>% 
  filter(LOCATION %in% low_inc_countries,
         SUBJECT == "TOT",
         MEASURE == "PC_GDP") %>% 
  select("LOCATION", "Value", "TIME")
colnames(health_spending_pcgdp_lo) <- c("COU", "Value", "Year")
```

```{r}
consult_vs_spend_hi <- inner_join(md_consult_per_capita_hi, health_spending_pcgdp_hi, by = c("COU" = "COU", "Year" = "Year"))
colnames(consult_vs_spend_hi)[3:5] <- c("MD consult", "Year", "Health Spending")

consult_vs_spend_lo <- inner_join(md_consult_per_capita_lo, health_spending_pcgdp_lo, by = c("COU" = "COU", "Year" = "Year"))
colnames(consult_vs_spend_lo)[3:5] <- c("MD consult", "Year", "Health Spending")


```

```{r}
p1 <- consult_vs_spend_hi %>% 
  ggplot(aes(x = Year, y = `MD consult`, fill = Country)) +         
  geom_col()

p2 <- consult_vs_spend_lo %>% 
  ggplot(aes(x = Year, y = `MD consult`, fill = Country)) +         
  geom_col()
```

```{r}
library(patchwork)
p1 + p2 +
  plot_annotation(title = "Doctor Consultations per Capita",
                  subtitle = "of High and Low Income Countries")
```

